-- Make bucket private
UPDATE storage.buckets
SET public = false,
    file_size_limit = 10485760, -- 10 MB
    allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']
WHERE id = 'consultation-uploads';

-- Drop the previous overly-permissive policies
DROP POLICY IF EXISTS "Anyone can upload consultation files" ON storage.objects;
DROP POLICY IF EXISTS "Anyone can read consultation files" ON storage.objects;

-- Allow anonymous patients to upload (the consultation form has no login),
-- but only into this bucket. The bucket-level mime/size limits enforce the rest.
CREATE POLICY "Anonymous can upload to consultation-uploads"
ON storage.objects FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'consultation-uploads');

-- No public SELECT policy on purpose. Files are served to the doctor
-- exclusively via short-lived signed URLs generated by the
-- `sign-consultation-files` edge function (uses service role).
